export const genresList = [
  "Action",
  "Casual",
  "RPG",
  "Strategy",
  "Adventure",
  "Simulation",
  "Sports",
];

export const languageList = [
  "Bulgarian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Finnish",
  "French",
  "German",
  "Greek",
  "Hungarian",
  "Italian",
  "Japanese",
  "Korean",
  "Norwegian",
  "Polish",
  "Portuguese",
  "Portuguese - Brazil",
  "Russian",
  "Romanian",
  "Simplified Chinese",
  "Spanish - Latin America",
  "Spanish - Spain",
  "Swedish",
  "Thai",
  "Traditional Chinese",
  "Turkish",
  "Ukrainian",
  "Vietnamese",
];
